---
version: '3'
services:
  base-build:
    build: .
    image: artifact-builder:latest
    working_dir: /root/artifact-builder
    environment:
      AWS_PROFILE: "${AWS_PROFILE}"
      PROJECT: "${PROJECT}"
      OS_RELEASE: "trusty-14.04"
    command: packer build -only=amazon-ebs -var "project=${PROJECT}" -var "os_release=${OS_RELEASE}" ubuntu-base-amd64.json
    volumes:
      - .:/root/artifact-builder:ro
      - ~/.aws/:/root/.aws:ro
